config/routes.rb
Rails.application.routes.draw do

  root to: 'urls#new'
  post '/' => 'urls#create'
  get '/show' => 'urls#show'
  get '/:url' => 'urls#redirect', as: :redirect

end

app/models/url.rb
class Url < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
require 'securerandom'

before_filter :validate_url, :only => :create

	def new
		@url = Url.new
	end

	def create
		url = params[:url][:original_url]

		original = Url.find_by(original_url: url)

		if original.nil?
			original = url
			new_url = Url.new
			new_url.original_url = original
			short_url = SecureRandom.hex(6)
			new_url.short_url = short_url
			new_url.save
		else
			short_url = original.short_url
		end

		redirect_to show_path(url: short_url)
	end

	def show
		@shortened_url = params[:url]
	    @target_url = request.host_with_port + '/' + @shortened_url
	end

	def redirect
		shortened_url = params[:url]
		url = Url.find_by(short_url: shortened_url)

		redirect_to url.original_url unless url.nil?
		redirect_to root_path, :flash => { :error => "Invalid URL!" } if url.nil?
	end

	

	def validate_url
		url = params[:url][:original_url]
		parsed = URI.parse(url)
		validated = %w( http https ).include?(parsed.scheme)
		redirect_to root_path, :flash => { :error => "Invalid URL!" } unless validated
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gapable</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Advent+Pro:300,400,600,700&amp;lang=en'%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<%= yield %>

</body>
</html>

app/views/urls/new.html.erb
<div class="container">
	<div class="page-title">
		<h1>Gapable URL Shortener</h1>
	</div>
	<div class="page-form">
		<%=form_for(Url.new, url: root_path, html: { method: :post }) do |f|%>
		 <%= f.text_field :original_url, placeholder: 'Enter Url Here', class: 'form-group', id: 'url-input'%><br/>
		 <%= f.submit "Generate URL", class: 'form-group', id: 'url-generate'%>
		<% end %>
	</div>
</div>


<script>
$(document).click(function() {
    $('.alert').hide();
});
</script>

app/views/urls/show.html.erb
<div class="container">
	<div class="page-title">
		<h1>Gapable URL Shortener</h1>
	</div>
	<div class="url-display">
		<h3>Your shortened url </h3>
		<%=link_to @target_url,redirect_path(url: @shortened_url), :target => '_blank', id: 'target-url'%>
		
	</div>
	<div class="go-home">
		<%= link_to 'Click Here To Go Back To Home', root_path %>
	</div>
</div>